image: stretch_gcc_cmake

stages:
    - build
    - test

build:
  stage: build

  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Testing ..
    - make

  artifacts:
    expire_in: 1 week
    paths:
      - build

test:
  stage: test

  script:
    - cd build
    - make check

  dependencies: [build]
